version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: rotimi98/vote:master
    build: ./vote
    ports:
    - 5001:80
    depends_on:
    - redis
    networks:
    - instavote
      
  result:
    image: rotimi98/result:master
    build: ./result    
    ports:
    - 5002:80
    depends_on:
    - db
    networks:
    - instavote
      
  worker:
    image: rotimi98/worker:master
    build: ./worker    
    depends_on:
    - redis
    - db
    networks:
    - instavote    

  redis:
    image: redis:alpine
    networks:
    - instavote

  db:
    image: postgres
  # image: postgres:9.4
    environment:
          #  - POSTGRES_PASSWORD:postgres
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - "db-data:/var/lib/postgresql/data"
    networks:
    - instavote  
